### ISSUE TITLE
Device does not react

### ISSUE THREAD

**Issue by rveenman** [harriedegroot/nl.novy.intouch#1]
Hi, I was thrilled that you have updated the app so that now supports full of the hood! Unfortunately, after (successful) installation, the hood does not seem to respond to Homey. Any thoughts?

**Comment by harriedegroot** [comment]
Do you have some additional information?
How can I reproduce the problem?
What steps did you take?
Does restarting Homey or re-installing the app/driver fix the issue?

Gr. Harrie

**Comment by rveenman** [comment]
Sure:

I am running the latest version of homey: 1.5.13 I believe.
I tried to restart Homey, remove the device, re-install the app.
The installation of the device goes fine, the Remote button press (used the on/off switch) is registered and the device is added. Then no response to the Homey controls at all.
Anything else I could share with you?

Gr Remi

On Sep 21, 2018, at 19:43, Harrie de Groot <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you have some additional information?
How can I reproduce the problem?
What steps did you take?
Does restarting Homey or re-installing the app/driver fix the issue?

Gr. Harrie

**Comment by harriedegroot** [comment]
Thanks for the info.
I didn't test on the latest firmware yet... I'm running latest stable
(1.5.11).
I know it contains a lot of changes in the rf drivers. Maybe it's time to
take a look :).
I need to find some time...but I'll keep you updated.

Gr. Harrie

**Comment by harriedegroot** [comment]
Resolved speed level bug
